// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiESgg-AFvErYv9uCA0sMCXA-HWCCBya8',
    appId: '1:885100442553:web:7f6295f0830a15cabebc68',
    messagingSenderId: '885100442553',
    projectId: 'tiktok-devgony',
    authDomain: 'tiktok-devgony.firebaseapp.com',
    storageBucket: 'tiktok-devgony.appspot.com',
    measurementId: 'G-TT5LG327MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZ7_0R_-larDeyb3jaPOJwzWhf6QqKug',
    appId: '1:971817649224:android:dc62d3c098d4ab7d24447d',
    messagingSenderId: '971817649224',
    projectId: 'tiktoklite-ac77a',
    storageBucket: 'tiktoklite-ac77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9yvzVPJRQLEMtb15_YxV0UujcoErK0s',
    appId: '1:971817649224:ios:729b995b307df27d24447d',
    messagingSenderId: '971817649224',
    projectId: 'tiktoklite-ac77a',
    storageBucket: 'tiktoklite-ac77a.firebasestorage.app',
    iosBundleId: 'com.example.tiktokCloneHenry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx1WQwL6yPtrqt3HLNE0k9ZQzI8Y9lzBg',
    appId: '1:885100442553:ios:bf49a254ce6e4426bebc68',
    messagingSenderId: '885100442553',
    projectId: 'tiktok-devgony',
    storageBucket: 'tiktok-devgony.appspot.com',
    androidClientId: '885100442553-jg1dbuima9o33bpbrki5fskft1b6p5ea.apps.googleusercontent.com',
    iosClientId: '885100442553-nfpeg3vt4qn405lda266a6sari1m3jcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}